var PicData = '{ "sites" : [' +
 '{"src":"./images/blue-mini/1.jpg" , "describe":"天空、风景、壁纸" },' + 
 '{"src":"./images/blue-mini/2.jpg" , "describe":"动物、天空、云"},' + 
 '{"src":"./images/blue-mini/3.jpg" , "describe":"动物、天空、云"},' + 
 '{"src":"./images/blue-mini/4.jpg" , "describe":"动物、河、湖、海"},' + 
 '{"src":"./images/blue-mini/5.jpg" , "describe":"天空、山、风景" },' + 
 '{"src":"./images/blue-mini/6.jpg" , "describe":"天空、云、风景" },' + 
 '{"src":"./images/blue-mini/7.jpg" , "describe":"天空、云" },' + 
 '{"src":"./images/blue-mini/8.jpg" , "describe":"天空、动物、风景" },' + 
 '{"src":"./images/blue-mini/9.jpg" , "describe":"天空、动物、风景" },' + 
 '{"src":"./images/blue-mini/10.jpg" , "describe":"天空、风景" },' + 
 '{"src":"./images/blue-mini/10.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/11.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/12.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/13.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/14.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/15.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/16.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/17.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/18.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/19.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/20.jpg" , "describe":"风景、壁纸、云" },' + 
 '{"src":"./images/blue-mini/21.jpg" , "describe":"风景、自然景色、壁纸动物" },' + 
 '{"src":"./images/blue-mini/22.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/23.jpg" , "describe":"风景、自然景色、壁纸、云、山、天空" },' + 
 '{"src":"./images/blue-mini/24.jpg" , "describe":"建筑、城市、风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/25.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸动物" },' + 
 '{"src":"./images/blue-mini/26.jpg" , "describe":"壁纸" },' + 
 '{"src":"./images/blue-mini/27.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/28.jpg" , "describe":"建筑、城市、山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/29.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/30.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/31.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/32.jpg" , "describe":"风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/33.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/34.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/35.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/36.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/37.jpg" , "describe":"风景、自然景色、壁纸、云、动物、天空" },' + 
 '{"src":"./images/blue-mini/38.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/39.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/40.jpg" , "describe":"山、河、湖、海" },' + 
 '{"src":"./images/blue-mini/41.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、山、天空" },' + 
 '{"src":"./images/blue-mini/42.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/43.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/44.jpg" , "describe":"风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/45.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、山、天空" },' + 
 '{"src":"./images/blue-mini/46.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/47.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/48.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/49.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/50.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/51.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/52.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/53.jpg" , "describe":"建筑、城市、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/54.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/55.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/56.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/57.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/58.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/59.jpg" , "describe":"建筑、城市、山、河、湖、海" },' + 
 '{"src":"./images/blue-mini/60.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/61.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/62.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/63.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/64.jpg" , "describe":"风景、自然景色、壁纸、云、山、天空" },' + 
 '{"src":"./images/blue-mini/65.jpg" , "describe":"风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/66.jpg" , "describe":"山、河、湖、海、山、天空" },' + 
 '{"src":"./images/blue-mini/67.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/68.jpg" , "describe":"风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/69.jpg" , "describe":"风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/70.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/71.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/72.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/73.jpg" , "describe":"风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/74.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/75.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/76.jpg" , "describe":"山、河、湖、海、山" },' + 
 '{"src":"./images/blue-mini/77.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/78.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、山、天空" },' + 
 '{"src":"./images/blue-mini/79.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/80.jpg" , "describe":"山、河、湖、海、云、山、天空" },' + 
 '{"src":"./images/blue-mini/81.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/82.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/83.jpg" , "describe":"建筑、城市、山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/84.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/85.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/86.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、天空" },' + 
 '{"src":"./images/blue-mini/87.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/88.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/89.jpg" , "describe":"山、河、湖、海、天空" },' + 
 '{"src":"./images/blue-mini/90.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/91.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、天空" },' + 
 '{"src":"./images/blue-mini/92.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/93.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/94.jpg" , "describe":"山、河、湖、海、天空" },' + 
 '{"src":"./images/blue-mini/95.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云" },' + 
 '{"src":"./images/blue-mini/96.jpg" , "describe":"风景、自然景色、壁纸天空" },' + 
 '{"src":"./images/blue-mini/97.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/98.jpg" , "describe":"山、河、湖、海、风景、自然景色、壁纸、云、山、天空" },' + 
 '{"src":"./images/blue-mini/99.jpg" , "describe":"风景、自然景色、壁纸" },' + 
 '{"src":"./images/blue-mini/100.jpg" , "describe":"建筑、城市、天空" },' + 
 '{"src":"./images/blue-mini/101.jpg" , "describe":"建筑、城市、天空" },' + 
 '{"src":"./images/blue-mini/102.jpg" , "describe":"江、河、湖、海、风景、自然景色、建筑、城市、天空" },' + 
 '{"src":"./images/blue-mini/103.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/104.jpg" , "describe":"风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/105.jpg" , "describe":"风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/106.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/107.jpg" , "describe":"山、江、河、湖、海、风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/108.jpg" , "describe":"天空" },' + 
 '{"src":"./images/blue-mini/109.jpg" , "describe":"山、江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/110.jpg" , "describe":"山、风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/111.jpg" , "describe":"山、风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/112.jpg" , "describe":"风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/113.jpg" , "describe":"山、江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/114.jpg" , "describe":"风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/115.jpg" , "describe":"风景、自然景色、天空" },' + 
 '{"src":"./images/blue-mini/116.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/117.jpg" , "describe":"动物、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/118.jpg" , "describe":"建筑、城市、天空" },' + 
 '{"src":"./images/blue-mini/119.jpg" , "describe":"江、河、湖、海、建筑、城市、天空" },' + 
 '{"src":"./images/blue-mini/120.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/121.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/122.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/123.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/124.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/125.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/126.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/127.jpg" , "describe":"江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/128.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/129.jpg" , "describe":"唯美" },' + 
 '{"src":"./images/blue-mini/130.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/131.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/132.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/133.jpg" , "describe":"山、风景" },' + 
 '{"src":"./images/blue-mini/134.jpg" , "describe":"山、江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/135.jpg" , "describe":"山、建筑、城市" },' + 
 '{"src":"./images/blue-mini/136.jpg" , "describe":"风景" },' + 
 '{"src":"./images/blue-mini/137.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/138.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/139.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/140.jpg" , "describe":"山、风景" },' + 
 '{"src":"./images/blue-mini/141.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/142.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/143.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/144.jpg" , "describe":"江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/145.jpg" , "describe":"山、江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/146.jpg" , "describe":"江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/147.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/148.jpg" , "describe":"山、江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/149.jpg" , "describe":"江、河、湖、海、天空" },' + 
 '{"src":"./images/blue-mini/150.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/151.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/152.jpg" , "describe":"江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/153.jpg" , "describe":"建筑、城市" },' + 
 '{"src":"./images/blue-mini/154.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/155.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/156.jpg" , "describe":"动物、江、河、湖、海、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/157.jpg" , "describe":"风景、自然景色、建筑、城市" },' + 
 '{"src":"./images/blue-mini/158.jpg" , "describe":"风景、自然景色" },' + 
 '{"src":"./images/blue-mini/159.jpg" , "describe":"山、风景、自然景色" },' + 
 '{"src":"./images/blue-mini/160.jpg" , "describe":"山、天空" } ]}';
